name: multi_calculator11
description: A multi-functional calculator app with localization support.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 多语言支持
  easy_localization: ^3.0.1

  # 你项目可能用到的其他依赖(根据需要保留/添加)
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true


  assets:
    - lib/assets/assets_lang/